import { mdToPdf } from 'md-to-pdf';

export async function generateReportPdf(data: any): Promise<Buffer> {
  const dateStr = new Date(data.created_at).toLocaleString();
  
  const threatLevel = data.ai_threat_level?.toUpperCase() ?? 'PENDING';
  const score = data.risk_score != null ? data.risk_score.toFixed(1) : '—';
  
  let markdown = `
# Phishing Triage Analyst Report
**Case #${data.id}** | **Date:** ${dateStr}

---

## 1. Email Summary
- **Subject:** ${data.subject ?? '(no subject)'}
- **Sender:** ${data.sender_display_name ? `${data.sender_display_name} <${data.sender_email}>` : data.sender_email ?? '—'}
- **Reply-To Mismatch:** ${data.reply_to_mismatch ? '⚠️ Yes' : 'No'}
- **Domain Spoofing:** ${data.display_name_domain_mismatch ? '⚠️ Yes' : 'No'}

## 2. Authentication
- **SPF:** ${data.spf_result ?? 'unknown'}
- **DKIM:** ${data.dkim_result ?? 'unknown'}
- **DMARC:** ${data.dmarc_result ?? 'unknown'}

## 3. Threat Assessment
- **Threat Level:** ${threatLevel}
- **Risk Score:** ${score} / 100
- **Kill Chain Stage:** ${data.ai_kill_chain_stage ?? '—'}
- **MITRE Technique:** ${data.ai_mitre_technique ?? '—'}

`;

  if (data.ai_red_flags && data.ai_red_flags.length > 0) {
    markdown += `## 4. Red Flags\n`;
    data.ai_red_flags.forEach((flag: string) => {
      markdown += `- ${flag}\n`;
    });
    markdown += `\n`;
  }

  if (data.ai_explanation) {
    markdown += `## 5. Analyst AI Explanation\n${data.ai_explanation}\n\n`;
  }

  if (data.extracted_urls && data.extracted_urls.length > 0) {
    markdown += `## 6. IOCs (URLs)\n`;
    markdown += `| URL | Domain | Mismatch |\n`;
    markdown += `|---|---|---|\n`;
    data.extracted_urls.forEach((u: any) => {
      markdown += `| \`${u.url}\` | ${u.domain} | ${u.textHrefMismatch ? 'Yes' : 'No'} |\n`;
    });
    markdown += `\n`;
  }

  markdown += `---\n*Generated by Phishing Triage System*`;

  // Use mdToPdf
  const pdf = await mdToPdf(
    { content: markdown },
    {
      pdf_options: { format: 'A4', margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' }, printBackground: true },
      launch_options: { args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'] }
    }
  );

  return pdf.content;
}
